---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create tag

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  determine-tag-version:
    name: Determine tag version
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    outputs:
      tag_version: ${{ steps.git-cliff.outputs.tag_version }}
    steps:
      - parallel:
          - name: Checkout
            uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
            with:
              fetch-depth: 0
              persist-credentials: false

          - name: Install git-cliff
            uses: taiki-e/install-action@742a3317eac7bd62f91cd888b4eead5e784ba833 # v2.87.1
            with:
              tool: git-cliff

      - name: Get tag version
        id: git-cliff
        env:
          # In order to avoid hitting the GitHub API rate limit
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag_version=$(git-cliff -c .github/cliff.toml --bumped-version --unreleased)
          echo "Next tag version is ${tag_version}"
          echo "tag_version=${tag_version}" >> "$GITHUB_OUTPUT"

  create-tag:
    name: Create tag
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    needs: determine-tag-version
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TAG_VERSION: ${{ needs.determine-tag-version.outputs.tag_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ssh-key: '${{ secrets.COMMIT_KEY }}'

      - parallel:
          - name: Pnpm Setup
            uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10

          - name: Set up Node.js
            uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
            with:
              node-version-file: 'package.json'
              # For workflows with elevated privileges we recommend disabling automatic caching.
              # https://github.com/actions/setup-node
              package-manager-cache: false

          - name: Configure git
            run: |
              git config --global user.name "${{ github.actor }}"
              git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Bump package.json
        run: npm version ${TAG_VERSION} --no-commit-hooks --no-git-tag-version

      - name: Commit updated files
        run: |
          git add package.json
          git commit -m "chore(release): prepare ${TAG_VERSION}"
          git push

      - name: Create git tag
        run: |
          git tag ${TAG_VERSION}
          git push origin ${TAG_VERSION}
